language: java
jdk:
- oraclejdk8
branches:
  only:
  - release
cache:
  directories:
  - $HOME/.m2 # speed up maven

before_install:
- openssl aes-256-cbc -K $encrypted_b1cdd46199e8_key -iv $encrypted_b1cdd46199e8_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d

