# https://hub.docker.com/_/mongo
version: '3.1'

services:
  mongo:
    container_name: cmltemplate-mongo
    image: mongo:4.4
    restart: always
    environment:
      WE_DONT_USE_AUTH: for_simplicity
    ##      MONGO_INITDB_ROOT_USERNAME: cmltemplate
    ##      MONGO_INITDB_ROOT_PASSWORD: cmltemplate
    ports:
      # https://docs.mongodb.com/manual/reference/default-mongodb-port/
      - '127.0.0.1:47017:27017'
    # Where our data will be persisted
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
# Names our volume
volumes:
  mongo_data:
    driver: local
  mongo_configdb:
    driver: local