# Documentation: https://hub.docker.com/_/mysql
version: '3.3'
services:
  db-mysql8:
    container_name: cmltemplate-mysql
    image: mysql:8.0
    restart: always
    command: >-
      mysqld
      --skip-ssl
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --slow_query_log=1
      --slow_query_log_file=/var/lib/mysql/slow.log
      --long_query_time=10
    environment:
      MYSQL_DATABASE: 'cmltemplate'
      MYSQL_USER: 'cmltemplate'
      MYSQL_PASSWORD: 'cmltemplate'
      MYSQL_ROOT_PASSWORD: 'cmltemplate'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '127.0.0.1:23306:3306'
    expose:
      # Opens port 3306 on the container to other services
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql
# Names our volume
volumes:
  # volume name will be 'cmltemplate-mysql_mysql_data'
  mysql_data:
    driver: local