# Documentation: https://hub.docker.com/_/rabbitmq
version: '3.3'
services:
  rabbit1:
    container_name: cmltemplate-rabbit
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit1
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
      # Where our data will be persisted
    volumes:
      - rabbit_data:/var/lib/rabbitmq
# Names our volume
volumes:
  rabbit_data:
    driver: local
